apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo-1
  template:
    metadata:
      labels:
        app: flask-demo-1
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: flask-demo
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
